# Required configuration
source: source
destination: public
code_dir: downloads/code
port: 4000

url: http://www.pwhite.org
title: Patrick White
permalink: /blog/:year/:month/:day/:title
subtitle: technologist & activist
author: Patrick White

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:

markdown: rdiscount
pygments: true
paginate: 10
recent_posts: 5
category_dir: /blog/categories
simple_search: http://google.com/search

# Optional configurations

# RSS feeds can list your email address if you like
email:

# Twitter
twitter_user: p6trick
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: pwhiteblog

# Google Analytics
google_analytics_tracking_id: UA-22089236-3
